server:
  type: default
  maxThreads: 1024
  applicationConnectors:
    - type: http
      port: 8444
  adminConnectors:
    - type: http
      port: 8447
client:
  student: ${student.api}
  subject: ${subject.api}