server:
  type: default
  maxThreads: 1024
  applicationConnectors:
    - type: http
      port: 8444
  adminConnectors:
    - type: http
      port: 8447
client:
  student: ${student.api}
  subject: ${subject.api}
db:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${db.host}:${db.port}/course_plan
  user: ${db.user}
  password: ${db.password}