apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: schl
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: student-service
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - env:
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: mysql
            - name: db_port
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: mysql
            - name: db_user
              value: student_service
            - name: db_password
              value: student_service
          image: docker.local/student-service:latest
          imagePullPolicy: Always
          name: student-service
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: schl
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: app-port
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: student-service
  sessionAffinity: None
  type: ClusterIP