apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  namespace: schl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - env:
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: mysql
            - name: db_port
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: mysql
            - name: db_user
              value: room_service
            - name: db_password
              value: room_service
          image: docker.local:5000/room-service:latest
          imagePullPolicy: Always
          name: room-service
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: room-service
  namespace: schl
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: app-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: room-service
  type: ClusterIP