ktor:
    application:
        modules:
            - dev.arkaan.schoolapp.subjectservice.SubjectServiceAppKt.setUp
    deployment:
        port: 8008

db:
    driver: com.mysql.cj.jdbc.Driver
    host: $DB_HOST
    port: $DB_PORT
    user: $DB_USER
    password: $DB_PASSWORD
    database: subjects