server:
  type: default
  maxThreads: 1024
  applicationConnectors:
    - type: http
      port: 8443
  adminConnectors:
    - type: http
      port: 8446
client:
  student: ${student.api}
  subject: ${subject.api}
  schedule: ${schedule.api}
db:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://${db_host}:${db_port}/course_plan
  user: ${db_user}
  password: ${db_password}